{% set name = "get-annotations" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/get-annotations-{{ version }}.tar.gz
  sha256: da7b69b8043237cc7f7ce5919e9cc59bd18fc4e2704b43eb34e3ba4fa9374bab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - get_annotations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shawwn/get-annotations
  summary: A backport of Python 3.10's inspect.get_annotations() function
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
